clc;
clear;
vectorized_data_path = '/Users/zhanghao/Documents/MATLAB/ML/HW3/email/vectorized_data';
predict_path = '/Users/zhanghao/Documents/MATLAB/ML/HW3/save_data';
best_predict_path = '/Users/zhanghao/Documents/MATLAB/ML/HW3/save_data/best_result';
PCAi = 512;
pca_vecs = load(fullfile(vectorized_data_path, 'pca_vecs_new.mat'));
pca_vecs = pca_vecs.pca_vecs;

pca_vecs = pca_vecs(:,1:PCAi);
train_hams_num = 3107;
train_spams_num = 1265;
test_num = 800;
train_label = [ones(train_spams_num,1);zeros(train_hams_num,1)];
trains_vecs = pca_vecs(1:train_hams_num+train_spams_num, :);
tests_vecs = pca_vecs(train_hams_num+train_spams_num+1:end, :);
%KNNmd = fitcknn(trains_vecs,train_label,'NumNeighbors',10,'Standardize',1);
%Naivemd = fitcnb(trains_vecs,train_label,'Distribution','mvmn');
tree = fitctree(trains_vecs,train_label,'OptimizeHyperparameters','auto');
%SVMModel = fitcsvm(trains_vecs,train_label,'KernelFunction','RBF');
%SVMModel = fitcsvm(trains_vecs,train_label);
%SVMModel = fitclinear(trains_vecs,train_label);
%SVMModel = fitckernel(trains_vecs,train_label);
%gprMdl = fitrgp(trains_vecs,train_label);
test_label = predict(tree,tests_vecs);
%test_label = round(test_label);
save(fullfile(predict_path,'test_labels.mat'), 'test_label');
b = find(test_label == 1);
best_result = load(fullfile(best_predict_path,'test_labels.mat'));
best_result = best_result.test_label;
c = find(best_result ~= test_label);
%best_result2 = load(fullfile(best_predict_path,'test_labels.mat'));
%best_result2 = best_result2.test_label;
%d = find(best_result ~= best_result2);